ALTER TABLE `orden_compra_item`
ADD COLUMN `recepcionado` TINYINT (1) NOT NULL DEFAULT 0,
ADD COLUMN `cantidad_recepcionada` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE movimiento_inventario
ADD COLUMN `orden_compra_item_id` INT NULL;

INSERT INTO estado_compras (codigo, nombre, tipo) VALUES
('OC_EMITIDA', 'EMITIDA', 'ORDEN_COMPRA'),
('OC_CANCELADA', 'CANCELADA', 'ORDEN_COMPRA'),
('OC_RECEPCIONADA', 'RECEPCIONADA', 'ORDEN_COMPRA'),
('OC_RECEP_PARCIAL', 'RECEPCIONADA_PARCIAL', 'ORDEN_COMPRA');