ALTER TABLE proveedor
ADD COLUMN created_at TIMESTAMP NULL,
ADD COLUMN created_by INT NULL,
ADD COLUMN updated_at TIMESTAMP NULL,
ADD COLUMN updated_by INT NULL,
ADD COLUMN deleted_at TIMESTAMP NULL,
ADD COLUMN deleted_by INT NULL;