
// Constantes de permisos del sistema
export const PERMISOS = {
  // Presupuestos
  PRESUPUESTOS_VER: 'PRESUPUESTOS_VER',
  PRESUPUESTOS_LISTAR: 'PRESUPUESTOS_LISTAR',
  PRESUPUESTOS_CREAR: 'PRESUPUESTOS_CREAR',
  PRESUPUESTOS_EDITAR: 'PRESUPUESTOS_EDITAR',
  PRESUPUESTOS_ELIMINAR: 'PRESUPUESTOS_ELIMINAR',
  PRESUPUESTOS_VERIFICAR_ALMACEN: 'PRESUPUESTOS_VERIFICAR_ALMACEN',
  PRESUPUESTOS_REGISTRAR_FECHA: 'PRESUPUESTOS_REGISTRAR_FECHA',
  PRESUPUESTOS_ACTUALIZAR_FECHA_ENTREGA: 'PRESUPUESTOS_ACTUALIZAR_FECHA_ENTREGA',
  PRESUPUESTOS_ACTUALIZAR_FECHA_FABRICACION: 'PRESUPUESTOS_ACTUALIZAR_FECHA_FABRICACION',
  PRESUPUESTOS_CONFIRMAR_ENTREGA: 'PRESUPUESTOS_CONFIRMAR_ENTREGA',
  PRESUPUESTOS_CERTIFICAR: 'PRESUPUESTOS_CERTIFICAR',
  PRESUPUESTOS_EXPORTAR_PDF: 'PRESUPUESTOS_EXPORTAR_PDF',
  PRESUPUESTOS_EXPORTAR_EXCEL: 'PRESUPUESTOS_EXPORTAR_EXCEL',
  PRESUPUESTOS_VER_ANALISIS: 'PRESUPUESTOS_VER_ANALISIS',
  PRESUPUESTOS_EXPORTAR_ORDEN_PDF: 'PRESUPUESTOS_EXPORTAR_ORDEN_PDF',
  PRESUPUESTOS_VER_MATERIALES_ANALISIS: 'PRESUPUESTOS_VER_MATERIALES_ANALISIS',
  PRESUPUESTOS_VER_SUMINISTROS_ANALISIS: 'PRESUPUESTOS_VER_SUMINISTROS_ANALISIS',
  PRESUPUESTOS_VER_MANO_DE_OBRA_ANALISIS: 'PRESUPUESTOS_VER_MANO_DE_OBRA_ANALISIS',
  PRESUPUESTOS_VER_PRODUCTOS_EXTRAS_ANALISIS: 'PRESUPUESTOS_VER_PRODUCTOS_EXTRAS_ANALISIS',
  PRESUPUESTOS_COSTOS_MATERIALES_VER: 'PRESUPUESTOS_COSTOS_MATERIALES_VER',
  PRESUPUESTOS_DASHBOARD: 'PRESUPUESTOS_DASHBOARD',
  PRESUPUESTOS_PRECIO_VENTA_VER: 'PRESUPUESTOS_PRECIO_VENTA_VER',

  PRESUPUESTOS_COSTEO_TECNICO_CREAR: 'PRESUPUESTOS_COSTEO_TECNICO_CREAR',
  PRESUPUESTOS_COSTEO_TECNICO_VER: 'PRESUPUESTOS_COSTEO_TECNICO_VER',
  PRESUPUESTOS_COSTEO_COMERCIAL_CREAR: 'PRESUPUESTOS_COSTEO_COMERCIAL_CREAR',
  PRESUPUESTOS_COSTEO_COMERCIAL_VER: 'PRESUPUESTOS_COSTEO_COMERCIAL_VER',
  PRESUPUESTOS_ENVIAR_A_ALMACEN: 'PRESUPUESTOS_ENVIAR_A_ALMACEN',
  PRESUPUESTOS_CARGAR_DISENO: 'PRESUPUESTOS_CARGAR_DISENO',
  PRESUPUESTOS_APROBAR_SERVICIO: 'PRESUPUESTOS_APROBAR_SERVICIO',

  // Filtros de Presupuestos (controlan qué presupuestos puede ver cada usuario)
  // Por defecto no se ve nada, cada permiso agrega un filtro OR
  PRESUPUESTOS_FILTRO_VER_PROPIOS: 'PRESUPUESTOS_FILTRO_VER_PROPIOS', // Ver solo mis presupuestos (vendedorId)
  PRESUPUESTOS_FILTRO_VER_MIS_PROCESOS: 'PRESUPUESTOS_FILTRO_VER_MIS_PROCESOS', // Ver presupuestos en mis procesos generales asignados
  PRESUPUESTOS_FILTRO_VER_TODOS: 'PRESUPUESTOS_FILTRO_VER_TODOS', // Ver todos los presupuestos sin restricción
  PRESUPUESTOS_FILTRO_VER_DISENO_COMPLETO: 'PRESUPUESTOS_FILTRO_VER_DISENO_COMPLETO', // Ver presupuestos con diseño completo
  PRESUPUESTOS_FILTRO_VER_COSTEO_COMPLETO: 'PRESUPUESTOS_FILTRO_VER_COSTEO_COMPLETO', // Ver presupuestos con costeo técnico completo
  PRESUPUESTOS_FILTRO_VER_COSTEO_COMERCIAL_COMPLETO: 'PRESUPUESTOS_FILTRO_VER_COSTEO_COMERCIAL_COMPLETO', // Ver presupuestos con costeo comercial completo
  PRESUPUESTOS_FILTRO_VER_PRODUCCION_COMPLETO: 'PRESUPUESTOS_FILTRO_VER_PRODUCCION_COMPLETO', // Ver presupuestos con producción completa

  // Clientes
  CLIENTES_VER: 'CLIENTES_VER',
  CLIENTES_CREAR: 'CLIENTES_CREAR',
  CLIENTES_EDITAR: 'CLIENTES_EDITAR',
  CLIENTES_ELIMINAR: 'CLIENTES_ELIMINAR',

  // Inventario
  INVENTARIO_VER: 'INVENTARIO_VER',
  INVENTARIO_CREAR: 'INVENTARIO_CREAR',
  INVENTARIO_EDITAR: 'INVENTARIO_EDITAR',
  INVENTARIO_ELIMINAR: 'INVENTARIO_ELIMINAR',
  INVENTARIO_INGRESO_MERCADERIA: 'INVENTARIO_INGRESO_MERCADERIA',
  INVENTARIO_EGRESO_MERCADERIA: 'INVENTARIO_EGRESO_MERCADERIA',
  INVENTARIO_VER_EXCEL: 'INVENTARIO_VER_EXCEL',
  INVENTARIO_IMPORTAR_EXCEL: 'INVENTARIO_IMPORTAR_EXCEL',

  // Usuarios
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_CREAR: 'USUARIOS_CREAR',
  USUARIOS_EDITAR: 'USUARIOS_EDITAR',
  USUARIOS_ELIMINAR: 'USUARIOS_ELIMINAR',

  // Roles y Permisos
  ROLES_VER: 'ROLES_VER',
  ROLES_CREAR: 'ROLES_CREAR',
  ROLES_EDITAR: 'ROLES_EDITAR',
  ROLES_ELIMINAR: 'ROLES_ELIMINAR',
  PERMISOS_GESTIONAR: 'PERMISOS_GESTIONAR',

  // Proveedores
  PROVEEDORES_VER: 'PROVEEDORES_VER',
  PROVEEDORES_CREAR: 'PROVEEDORES_CREAR',
  PROVEEDORES_EDITAR: 'PROVEEDORES_EDITAR',
  PROVEEDORES_ELIMINAR: 'PROVEEDORES_ELIMINAR',


  PROVEEDORES_RUBRO_VER: 'PROVEEDORES_RUBRO_VER',
  PROVEEDORES_RUBRO_CREAR: 'PROVEEDORES_RUBRO_CREAR',
  PROVEEDORES_RUBRO_EDITAR: 'PROVEEDORES_RUBRO_EDITAR',
  PROVEEDORES_RUBRO_ELIMINAR: 'PROVEEDORES_RUBRO_ELIMINAR',

  // Alquileres
  ALQUILERES_VER: 'ALQUILERES_VER',
  ALQUILERES_CREAR: 'ALQUILERES_CREAR',
  ALQUILERES_EDITAR: 'ALQUILERES_EDITAR',
  ALQUILERES_ELIMINAR: 'ALQUILERES_ELIMINAR',
  ALQUILERES_EXPORTAR_EXCEL: 'ALQUILERES_EXPORTAR_EXCEL',
  ALQUILERES_REPORTE_FACTURACION: 'ALQUILERES_REPORTE_FACTURACION',
  ALQUILERES_REPORTE_CANTIDAD_RECURSOS: 'ALQUILERES_REPORTE_CANTIDAD_RECURSOS',
  ALQUILERES_REPORTE_ESTADO_RECURSOS: 'ALQUILERES_REPORTE_ESTADO_RECURSOS',

  ALQUILERES_COBRANZAS_VER: 'ALQUILERES_COBRANZAS_VER',
  ALQUILERES_COBRANZAS_CREAR: 'ALQUILERES_COBRANZAS_CREAR',
  ALQUILERES_COBRANZAS_EDITAR: 'ALQUILERES_COBRANZAS_EDITAR',
  ALQUILERES_COBRANZAS_ELIMINAR: 'ALQUILERES_COBRANZAS_ELIMINAR',

  ALQUILERES_FACTURAS_VER: 'ALQUILERES_FACTURAS_VER',
  ALQUILERES_FACTURAS_CREAR: 'ALQUILERES_FACTURAS_CREAR',
  ALQUILERES_FACTURAS_EDITAR: 'ALQUILERES_FACTURAS_EDITAR',
  ALQUILERES_FACTURAS_ELIMINAR: 'ALQUILERES_FACTURAS_ELIMINAR',

  ALQUILERES_MANTENIMIENTO_CREAR: 'ALQUILERES_MANTENIMIENTO_CREAR',
  ALQUILERES_MANTENIMIENTO_VER: 'ALQUILERES_MANTENIMIENTO_VER',
  ALQUILERES_MANTENIMIENTO_EDITAR: 'ALQUILERES_MANTENIMIENTO_EDITAR',
  ALQUILERES_MANTENIMIENTO_ELIMINAR: 'ALQUILERES_MANTENIMIENTO_ELIMINAR',

  ALQUILERES_PRECIO_CREAR: 'ALQUILERES_PRECIO_CREAR',
  ALQUILERES_PRECIO_VER: 'ALQUILERES_PRECIO_VER',
  ALQUILERES_PRECIO_EDITAR: 'ALQUILERES_PRECIO_EDITAR',
  ALQUILERES_PRECIO_ELIMINAR: 'ALQUILERES_PRECIO_ELIMINAR',


  ALQUILERES_RECURSOS_VER: 'ALQUILERES_RECURSOS_VER',
  ALQUILERES_RECURSOS_CREAR: 'ALQUILERES_RECURSOS_CREAR',
  ALQUILERES_RECURSOS_EDITAR: 'ALQUILERES_RECURSOS_EDITAR',
  ALQUILERES_RECURSOS_ELIMINAR: 'ALQUILERES_RECURSOS_ELIMINAR',
  ALQUILERES_RECURSOS_EXCEL: 'ALQUILERES_RECURSOS_EXCEL',

  CARTELES_VER: 'CARTELES_VER',
  CARTELES_CREAR: 'CARTELES_CREAR',
  CARTELES_EDITAR: 'CARTELES_EDITAR',
  CARTELES_ELIMINAR: 'CARTELES_ELIMINAR',

  TRAILERS_VER: 'TRAILERS_VER',
  TRAILERS_CREAR: 'TRAILERS_CREAR',
  TRAILERS_EDITAR: 'TRAILERS_EDITAR',
  TRAILERS_ELIMINAR: 'TRAILERS_ELIMINAR',

  ARCHIVOS_CREAR: 'ARCHIVOS_CREAR',
  ARCHIVOS_VER: 'ARCHIVOS_VER',
  ARCHIVOS_EDITAR: 'ARCHIVOS_EDITAR',
  ARCHIVOS_ELIMINAR: 'ARCHIVOS_ELIMINAR',

  // Facturas
  FACTURA_VER: 'FACTURA_VER',
  FACTURA_CREAR: 'FACTURA_CREAR',
  FACTURA_EDITAR: 'FACTURA_EDITAR',
  FACTURA_ELIMINAR: 'FACTURA_ELIMINAR',

  // Cobros
  COBRO_VER: 'COBRO_VER',
  COBRO_CREAR: 'COBRO_CREAR',
  COBRO_EDITAR: 'COBRO_EDITAR',
  COBRO_ELIMINAR: 'COBRO_ELIMINAR',

  AREA_CREAR: 'AREA_CREAR',
  AREA_VER: 'AREA_VER',
  AREA_EDITAR: 'AREA_EDITAR',
  AREA_ELIMINAR: 'AREA_ELIMINAR',

  // Personas
  PERSONA_CREAR: 'PERSONA_CREAR',
  PERSONA_VER: 'PERSONA_VER',
  PERSONA_EDITAR: 'PERSONA_EDITAR',
  PERSONA_ELIMINAR: 'PERSONA_ELIMINAR',

  // Jornadas
  JORNADA_CREAR: 'JORNADA_CREAR',
  JORNADA_VER: 'JORNADA_VER',
  JORNADA_EDITAR: 'JORNADA_EDITAR',
  JORNADA_ELIMINAR: 'JORNADA_ELIMINAR',
  JORNADA_INICIAR: 'JORNADA_INICIAR',
  JORNADA_FINALIZAR: 'JORNADA_FINALIZAR',

  // Refrigerio
  REFRIGERIO_INICIAR: 'REFRIGERIO_INICIAR',
  REFRIGERIO_FINALIZAR: 'REFRIGERIO_FINALIZAR',

  AUDITORIA_CREAR: 'AUDITORIA_CREAR',
  AUDITORIA_VER: 'AUDITORIA_VER',
  AUDITORIA_PRESUPUESTO_HISTORIAL: 'AUDITORIA_PRESUPUESTO_HISTORIAL',
  AUDITORIA_EDITAR: 'AUDITORIA_EDITAR',
  AUDITORIA_ELIMINAR: 'AUDITORIA_ELIMINAR',

  // Cashflow/Finanzas
  FINANZAS_CREAR_TRANSACCION: 'FINANZAS_CREAR_TRANSACCION',
  FINANZAS_EDITAR_TRANSACCION: 'FINANZAS_EDITAR_TRANSACCION',
  FINANZAS_ELIMINAR_TRANSACCION: 'FINANZAS_ELIMINAR_TRANSACCION',


  // Costeo

  AFIP_CONSULTAR_PADRON: 'AFIP_CONSULTAR_PADRON',

  BANCOS_CREAR: 'BANCOS_CREAR',
  BANCOS_VER: 'BANCOS_VER',
  BANCOS_EDITAR: 'BANCOS_EDITAR',
  BANCOS_ELIMINAR: 'BANCOS_ELIMINAR',
  BANCOS_TRANSFERIR: 'BANCOS_TRANSFERIR',

  BANCOS_SALDO_CREAR: 'BANCOS_SALDO_CREAR',
  BANCOS_SALDO_VER: 'BANCOS_SALDO_VER',
  BANCOS_SALDO_EDITAR: 'BANCOS_SALDO_EDITAR',
  BANCOS_SALDO_ELIMINAR: 'BANCOS_SALDO_ELIMINAR',

  CASHFLOW_CATEGORIA_EDITAR: 'CASHFLOW_CATEGORIA_EDITAR',
  CASHFLOW_CATEGORIA_ELIMINAR: 'CASHFLOW_CATEGORIA_ELIMINAR',
  CASHFLOW_CATEGORIA_CREAR: 'CASHFLOW_CATEGORIA_CREAR',
  CASHFLOW_CATEGORIA_VER: 'CASHFLOW_CATEGORIA_VER',

  CASHFLOW_RUBRO_EDITAR: 'CASHFLOW_RUBRO_EDITAR',
  CASHFLOW_RUBRO_ELIMINAR: 'CASHFLOW_RUBRO_ELIMINAR',
  CASHFLOW_RUBRO_CREAR: 'CASHFLOW_RUBRO_CREAR',
  CASHFLOW_RUBRO_VER: 'CASHFLOW_RUBRO_VER',

  CASHFLOW_AGRUPACION_VER: 'CASHFLOW_AGRUPACION_VER',
  CASHFLOW_AGRUPACION_CREAR: 'CASHFLOW_AGRUPACION_CREAR',
  CASHFLOW_AGRUPACION_EDITAR: 'CASHFLOW_AGRUPACION_EDITAR',
  CASHFLOW_AGRUPACION_ELIMINAR: 'CASHFLOW_AGRUPACION_ELIMINAR',

  CASHFLOW_VER: 'CASHFLOW_VER',
  CASHFLOW_CREAR: 'CASHFLOW_CREAR',
  CASHFLOW_EDITAR: 'CASHFLOW_EDITAR',
  CASHFLOW_ELIMINAR: 'CASHFLOW_ELIMINAR',
  CASHFLOW_CONCILIAR: 'CASHFLOW_CONCILIAR',
  CASHFLOW_REPORTES: 'CASHFLOW_REPORTES',

  INVENTARIO_FAMILIA_VER: 'INVENTARIO_FAMILIA_VER',
  INVENTARIO_FAMILIA_CREAR: 'INVENTARIO_FAMILIA_CREAR',
  INVENTARIO_FAMILIA_EDITAR: 'INVENTARIO_FAMILIA_EDITAR',
  INVENTARIO_FAMILIA_ELIMINAR: 'INVENTARIO_FAMILIA_ELIMINAR',


  INVENTARIO_CATEGORIA_VER: 'INVENTARIO_CATEGORIA_VER',
  INVENTARIO_CATEGORIA_CREAR: 'INVENTARIO_CATEGORIA_CREAR',
  INVENTARIO_CATEGORIA_EDITAR: 'INVENTARIO_CATEGORIA_EDITAR',
  INVENTARIO_CATEGORIA_ELIMINAR: 'INVENTARIO_CATEGORIA_ELIMINAR',

  CENTRO_COSTO_VER: 'CENTRO_COSTO_VER',
  CENTRO_COSTO_CREAR: 'CENTRO_COSTO_CREAR',
  CENTRO_COSTO_EDITAR: 'CENTRO_COSTO_EDITAR',
  CENTRO_COSTO_ELIMINAR: 'CENTRO_COSTO_ELIMINAR',


  CONTRATO_MARCO_CREAR: 'CONTRATO_MARCO_CREAR',
  CONTRATO_MARCO_VER: 'CONTRATO_MARCO_VER',
  CONTRATO_MARCO_EDITAR: 'CONTRATO_MARCO_EDITAR',
  CONTRATO_MARCO_ELIMINAR: 'CONTRATO_MARCO_ELIMINAR',
  CONTRATO_MARCO_REPORTES: 'CONTRATO_MARCO_REPORTES',

  CONTRATO_MARCO_PRESUPUESTO_CREAR: 'CONTRATO_MARCO_PRESUPUESTO_CREAR',
  CONTRATO_MARCO_PRESUPUESTO_VER: 'CONTRATO_MARCO_PRESUPUESTO_VER',
  CONTRATO_MARCO_PRESUPUESTO_EDITAR: 'CONTRATO_MARCO_PRESUPUESTO_EDITAR',
  CONTRATO_MARCO_PRESUPUESTO_ELIMINAR: 'CONTRATO_MARCO_PRESUPUESTO_ELIMINAR',

  CONTRATO_MARCO_TALONARIO_CREAR: 'CONTRATO_MARCO_TALONARIO_CREAR',
  CONTRATO_MARCO_TALONARIO_VER: 'CONTRATO_MARCO_TALONARIO_VER',
  CONTRATO_MARCO_TALONARIO_EDITAR: 'CONTRATO_MARCO_TALONARIO_EDITAR',
  CONTRATO_MARCO_TALONARIO_ELIMINAR: 'CONTRATO_MARCO_TALONARIO_ELIMINAR',

  INDICE_CREAR: 'INDICE_CREAR',
  INDICE_VER: 'INDICE_VER',
  INDICE_EDITAR: 'INDICE_EDITAR',
  INDICE_ELIMINAR: 'INDICE_ELIMINAR',

  INVENTARIO_RESERVA_VER: 'INVENTARIO_RESERVA_VER',
  INVENTARIO_RESERVA_CREAR: 'INVENTARIO_RESERVA_CREAR',
  INVENTARIO_RESERVA_EDITAR: 'INVENTARIO_RESERVA_EDITAR',
  INVENTARIO_RESERVA_ELIMINAR: 'INVENTARIO_RESERVA_ELIMINAR',

  // Reservas (agrupación de inventario_reservas)
  RESERVA_VER: 'RESERVA_VER',
  RESERVA_CREAR: 'RESERVA_CREAR',
  RESERVA_EDITAR: 'RESERVA_EDITAR',
  RESERVA_ELIMINAR: 'RESERVA_ELIMINAR',


  MENSAJES_CREAR: 'MENSAJES_CREAR',
  MENSAJES_VER: 'MENSAJES_VER',
  MENSAJES_EDITAR: 'MENSAJES_EDITAR',
  MENSAJES_ELIMINAR: 'MENSAJES_ELIMINAR',

  METODO_PAGO_CREAR: 'METODO_PAGO_CREAR',
  METODO_PAGO_VER: 'METODO_PAGO_VER',
  METODO_PAGO_EDITAR: 'METODO_PAGO_EDITAR',
  METODO_PAGO_ELIMINAR: 'METODO_PAGO_ELIMINAR',

  PLAZO_PAGO_CREAR: 'PLAZO_PAGO_CREAR',
  PLAZO_PAGO_VER: 'PLAZO_PAGO_VER',
  PLAZO_PAGO_EDITAR: 'PLAZO_PAGO_EDITAR',
  PLAZO_PAGO_ELIMINAR: 'PLAZO_PAGO_ELIMINAR',

  SOLCOM_CREAR: 'SOLCOM_CREAR',
  SOLCOM_VER: 'SOLCOM_VER',
  SOLCOM_EDITAR: 'SOLCOM_EDITAR',
  SOLCOM_ELIMINAR: 'SOLCOM_ELIMINAR',
  SOLCOM_FINALIZAR: 'SOLCOM_FINALIZAR',
  SOLCOM_ASIGNAR: 'SOLCOM_ASIGNAR', // Permite asignar una SOLCOM a un comprador
  SOLCOM_MODIFICAR_ESTADO: 'SOLCOM_MODIFICAR_ESTADO', // Permite cambiar el estado de una SOLCOM

  // Filtros de SOLCOM (controlan qué SOLCOM puede ver cada usuario)
  // Por defecto no se ve nada, cada permiso agrega un filtro OR
  SOLCOM_FILTRO_VER_PROPIAS: 'SOLCOM_FILTRO_VER_PROPIAS', // Ver solo SOLCOM creadas por mí (usuarioId)
  SOLCOM_FILTRO_VER_TODAS: 'SOLCOM_FILTRO_VER_TODAS', // Ver todas las SOLCOM sin restricción
  SOLCOM_FILTRO_VER_PENDIENTES: 'SOLCOM_FILTRO_VER_PENDIENTES', // Ver SOLCOM con estado SOLC_INI
  SOLCOM_FILTRO_VER_APROBADAS: 'SOLCOM_FILTRO_VER_APROBADAS', // Ver SOLCOM con estado SOLC_AP
  SOLCOM_FILTRO_VER_RECHAZADAS: 'SOLCOM_FILTRO_VER_RECHAZADAS', // Ver SOLCOM con estado SOLC_RECH
  SOLCOM_FILTRO_VER_FINALIZADAS: 'SOLCOM_FILTRO_VER_FINALIZADAS', // Ver SOLCOM con estado SOLC_FIN

  OFERTA_CREAR: 'OFERTA_CREAR',
  OFERTA_VER: 'OFERTA_VER',
  OFERTA_EDITAR: 'OFERTA_EDITAR',
  OFERTA_ELIMINAR: 'OFERTA_ELIMINAR',
  OFERTA_ENVIAR_A_VALIDAR: 'OFERTA_ENVIAR_A_VALIDAR',
  OFERTA_RECHAZAR: 'OFERTA_RECHAZAR',
  OFERTA_APROBAR: 'OFERTA_APROBAR',
  OFERTA_VER_APROBACIONES: 'OFERTA_VER_APROBACIONES',
  OFERTA_APROBAR_TECNICA: 'OFERTA_APROBAR_TECNICA',
  OFERTA_APROBAR_CALIDAD: 'OFERTA_APROBAR_CALIDAD',
  OFERTA_APROBAR_GERENCIA: 'OFERTA_APROBAR_GERENCIA',
  OFERTA_APROBAR_ADMINISTRACION: 'OFERTA_APROBAR_ADMINISTRACION',

  ORDEN_COMPRA_CREAR: 'ORDEN_COMPRA_CREAR',
  ORDEN_COMPRA_VER: 'ORDEN_COMPRA_VER',
  ORDEN_COMPRA_EDITAR: 'ORDEN_COMPRA_EDITAR',
  ORDEN_COMPRA_ELIMINAR: 'ORDEN_COMPRA_ELIMINAR',
  ORDEN_COMPRA_CANCELAR: 'ORDEN_COMPRA_CANCELAR',

  CUENTA_CONTABLE_CREAR: 'CUENTA_CONTABLE_CREAR',
  CUENTA_CONTABLE_VER: 'CUENTA_CONTABLE_VER',
  CUENTA_CONTABLE_EDITAR: 'CUENTA_CONTABLE_EDITAR',
  CUENTA_CONTABLE_ELIMINAR: 'CUENTA_CONTABLE_ELIMINAR',

  MOVIMIENTO_INVENTARIO_CREAR: 'MOVIMIENTO_INVENTARIO_CREAR',
  MOVIMIENTO_INVENTARIO_VER: 'MOVIMIENTO_INVENTARIO_VER',
  MOVIMIENTO_INVENTARIO_EDITAR: 'MOVIMIENTO_INVENTARIO_EDITAR',
  MOVIMIENTO_INVENTARIO_ELIMINAR: 'MOVIMIENTO_INVENTARIO_ELIMINAR',

  PRESUPUESTO_COBRO_VER: 'PRESUPUESTO_COBRO_VER',
  PRESUPUESTO_COBRO_CREAR: 'PRESUPUESTO_COBRO_CREAR',
  PRESUPUESTO_COBRO_EDITAR: 'PRESUPUESTO_COBRO_EDITAR',
  PRESUPUESTO_COBRO_ELIMINAR: 'PRESUPUESTO_COBRO_ELIMINAR',

  PRESUPUESTO_FACTURACION_VER: 'PRESUPUESTO_FACTURACION_VER',
  PRESUPUESTO_FACTURACION_CREAR: 'PRESUPUESTO_FACTURACION_CREAR',
  PRESUPUESTO_FACTURACION_EDITAR: 'PRESUPUESTO_FACTURACION_EDITAR',
  PRESUPUESTO_FACTURACION_ELIMINAR: 'PRESUPUESTO_FACTURACION_ELIMINAR',

  PRESUPUESTO_ITEM_VER: 'PRESUPUESTO_ITEM_VER',
  PRESUPUESTO_ITEM_CREAR: 'PRESUPUESTO_ITEM_CREAR',
  PRESUPUESTO_ITEM_EDITAR: 'PRESUPUESTO_ITEM_EDITAR',
  PRESUPUESTO_ITEM_ELIMINAR: 'PRESUPUESTO_ITEM_ELIMINAR',
  PRESUPUESTO_ITEM_ASIGNAR_RECETAS: 'PRESUPUESTO_ITEM_ASIGNAR_RECETAS',

  NOTIFICACIONES_VER: 'NOTIFICACIONES_VER',
  NOTIFICACIONES_CREAR: 'NOTIFICACIONES_CREAR',
  NOTIFICACIONES_EDITAR: 'NOTIFICACIONES_EDITAR',
  NOTIFICACIONES_ELIMINAR: 'NOTIFICACIONES_ELIMINAR',


  PRESUPUESTO_MANO_DE_OBRA_VER: 'PRESUPUESTO_MANO_DE_OBRA_VER',
  PRESUPUESTO_MANO_DE_OBRA_CREAR: 'PRESUPUESTO_MANO_DE_OBRA_CREAR',
  PRESUPUESTO_MANO_DE_OBRA_EDITAR: 'PRESUPUESTO_MANO_DE_OBRA_EDITAR',
  PRESUPUESTO_MANO_DE_OBRA_ELIMINAR: 'PRESUPUESTO_MANO_DE_OBRA_ELIMINAR',

  PRESUPUESTO_SUMINISTROS_VER: 'PRESUPUESTO_SUMINISTROS_VER',
  PRESUPUESTO_SUMINISTROS_CREAR: 'PRESUPUESTO_SUMINISTROS_CREAR',
  PRESUPUESTO_SUMINISTROS_EDITAR: 'PRESUPUESTO_SUMINISTROS_EDITAR',
  PRESUPUESTO_SUMINISTROS_ELIMINAR: 'PRESUPUESTO_SUMINISTROS_ELIMINAR',

  PRESUPUESTO_MATERIALES_VER: 'PRESUPUESTO_MATERIALES_VER',
  PRESUPUESTO_MATERIALES_CREAR: 'PRESUPUESTO_MATERIALES_CREAR',
  PRESUPUESTO_MATERIALES_EDITAR: 'PRESUPUESTO_MATERIALES_EDITAR',
  PRESUPUESTO_MATERIALES_ELIMINAR: 'PRESUPUESTO_MATERIALES_ELIMINAR',

  PRESUPUESTO_TRABAJOS_VER: 'PRESUPUESTO_TRABAJOS_VER',
  PRESUPUESTO_TRABAJOS_CREAR: 'PRESUPUESTO_TRABAJOS_CREAR',
  PRESUPUESTO_TRABAJOS_EDITAR: 'PRESUPUESTO_TRABAJOS_EDITAR',
  PRESUPUESTO_TRABAJOS_ELIMINAR: 'PRESUPUESTO_TRABAJOS_ELIMINAR',

  PROCESO_GENERAL_VER: 'PROCESO_GENERAL_VER',
  PROCESO_GENERAL_CREAR: 'PROCESO_GENERAL_CREAR',
  PROCESO_GENERAL_EDITAR: 'PROCESO_GENERAL_EDITAR',
  PROCESO_GENERAL_ELIMINAR: 'PROCESO_GENERAL_ELIMINAR',

  PRESUPUESTO_PRODUCCION_VER: 'PRESUPUESTO_PRODUCCION_VER',
  PRESUPUESTO_PRODUCCION_CREAR: 'PRESUPUESTO_PRODUCCION_CREAR',
  PRESUPUESTO_PRODUCCION_EDITAR: 'PRESUPUESTO_PRODUCCION_EDITAR',
  PRESUPUESTO_PRODUCCION_ELIMINAR: 'PRESUPUESTO_PRODUCCION_ELIMINAR',


  PRESUPUESTO_RECETA_VER: 'PRESUPUESTO_RECETA_VER',
  PRESUPUESTO_RECETA_CREAR: 'PRESUPUESTO_RECETA_CREAR',
  PRESUPUESTO_RECETA_EDITAR: 'PRESUPUESTO_RECETA_EDITAR',
  PRESUPUESTO_RECETA_ELIMINAR: 'PRESUPUESTO_RECETA_ELIMINAR',

  // Rutas del menú
  RUTA_DASHBOARD: 'RUTA_DASHBOARD',
  RUTA_USUARIOS: 'RUTA_USUARIOS',
  RUTA_PRODUCTOS: 'RUTA_PRODUCTOS',
  RUTA_CATEGORIAS: 'RUTA_CATEGORIAS',
  RUTA_PRESUPUESTOS: 'RUTA_PRESUPUESTOS',
  RUTA_PRESUPUESTOS_ESTADISTICAS: 'RUTA_PRESUPUESTOS_ESTADISTICAS',
  RUTA_CLIENTES: 'RUTA_CLIENTES',
  RUTA_RECURSOS: 'RUTA_RECURSOS',
  RUTA_CARTELES: 'RUTA_CARTELES',
  RUTA_TRAILERS: 'RUTA_TRAILERS',
  RUTA_INDICES: 'RUTA_INDICES',
  RUTA_ALQUILERES: 'RUTA_ALQUILERES',
  RUTA_AREAS: 'RUTA_AREAS',
  RUTA_PERSONAS: 'RUTA_PERSONAS',
  RUTA_RECETAS: 'RUTA_RECETAS',
  RUTA_ACTUALIZACIONES: 'RUTA_ACTUALIZACIONES',
  RUTA_MOVIMIENTOS_INVENTARIO: 'RUTA_MOVIMIENTOS_INVENTARIO',
  RUTA_CONTRATOS_MARCO: 'RUTA_CONTRATOS_MARCO',
  RUTA_PROVEEDORES: 'RUTA_PROVEEDORES',
  RUTA_RUBROS: 'RUTA_RUBROS',
  RUTA_METODO_PAGO: 'RUTA_METODO_PAGO',
  RUTA_CASHFLOW: 'RUTA_CASHFLOW',
  RUTA_CASHFLOW_CATEGORIAS: 'RUTA_CASHFLOW_CATEGORIAS',
  RUTA_CASHFLOW_RUBROS: 'RUTA_CASHFLOW_RUBROS',
  RUTA_CASHFLOW_AGRUPACIONES: 'RUTA_CASHFLOW_AGRUPACIONES',
  RUTA_CASHFLOW_ESTADISTICAS: 'RUTA_CASHFLOW_ESTADISTICAS',
  RUTA_BANCOS: 'RUTA_BANCOS',
  RUTA_CENTRO_COSTO: 'RUTA_CENTRO_COSTO',
  RUTA_ROLES: 'RUTA_ROLES',
  RUTA_PLAZO_PAGO: 'RUTA_PLAZO_PAGO',
  RUTA_SOLCOM: 'RUTA_SOLCOM',
  RUTA_SOLCOM_CREAR: 'RUTA_SOLCOM_CREAR',
  RUTA_SOLCOM_PENDIENTES_AUTORIZACION: 'RUTA_SOLCOM_PENDIENTES_AUTORIZACION',
  RUTA_SOLCOM_ACTIVAS: 'RUTA_SOLCOM_ACTIVAS',
  RUTA_OFERTAS: 'RUTA_OFERTAS',
  RUTA_TODAS_OFERTAS: 'RUTA_TODAS_OFERTAS',
  RUTA_MIS_OFERTAS: 'RUTA_MIS_OFERTAS',
  RUTA_OFERTAS_CREAR: 'RUTA_OFERTAS_CREAR',
  RUTA_CUENTA_CONTABLE: 'RUTA_CUENTA_CONTABLE',
  RUTA_CUENTA_CONTABLE_CREAR: 'RUTA_CUENTA_CONTABLE_CREAR',
  RUTA_ORDEN_COMPRA: 'RUTA_ORDEN_COMPRA',
  RUTA_CONTACTO_TIPO: 'RUTA_CONTACTO_TIPO',
  RUTA_CONTACTO_CASOS: 'RUTA_CONTACTO_CASOS',
  RUTA_CALENDARIO_CONTACTOS: 'RUTA_CALENDARIO_CONTACTOS',
  RUTA_PLANIFICACIONES: 'RUTA_PLANIFICACIONES',


  PRESUPUESTOS_PRODUCCION_DASHBOARD: 'PRESUPUESTOS_PRODUCCION_DASHBOARD',
  PRESUPUESTOS_SERVICIOS_DASHBOARD: 'PRESUPUESTOS_SERVICIOS_DASHBOARD',
  ALQUILERES_DASHBOARD: 'ALQUILERES_DASHBOARD',

  // Role Proceso General
  ROLE_PROCESO_GENERAL_VER: 'ROLE_PROCESO_GENERAL_VER',
  ROLE_PROCESO_GENERAL_CREAR: 'ROLE_PROCESO_GENERAL_CREAR',
  ROLE_PROCESO_GENERAL_EDITAR: 'ROLE_PROCESO_GENERAL_EDITAR',
  ROLE_PROCESO_GENERAL_ELIMINAR: 'ROLE_PROCESO_GENERAL_ELIMINAR',

  // Contacto Tipo
  CONTACTO_TIPO_VER: 'CONTACTO_TIPO_VER',
  CONTACTO_TIPO_CREAR: 'CONTACTO_TIPO_CREAR',
  CONTACTO_TIPO_EDITAR: 'CONTACTO_TIPO_EDITAR',
  CONTACTO_TIPO_ELIMINAR: 'CONTACTO_TIPO_ELIMINAR',

  // Contacto Caso
  CONTACTO_CASO_VER: 'CONTACTO_CASO_VER',
  CONTACTO_CASO_CREAR: 'CONTACTO_CASO_CREAR',
  CONTACTO_CASO_EDITAR: 'CONTACTO_CASO_EDITAR',
  CONTACTO_CASO_ELIMINAR: 'CONTACTO_CASO_ELIMINAR',

  // Contacto
  CONTACTO_VER: 'CONTACTO_VER',
  CONTACTO_CREAR: 'CONTACTO_CREAR',
  CONTACTO_EDITAR: 'CONTACTO_EDITAR',
  CONTACTO_ELIMINAR: 'CONTACTO_ELIMINAR',

  // Flota
  FLOTA_VER: 'FLOTA_VER',
  FLOTA_CREAR: 'FLOTA_CREAR',
  FLOTA_EDITAR: 'FLOTA_EDITAR',
  FLOTA_ELIMINAR: 'FLOTA_ELIMINAR',

  // Ubicaciones
  UBICACION_VER: 'UBICACION_VER',
  UBICACION_CREAR: 'UBICACION_CREAR',
  UBICACION_EDITAR: 'UBICACION_EDITAR',
  UBICACION_ELIMINAR: 'UBICACION_ELIMINAR',

  // Configuración - Compras
  COMPRAS_CONFIG: 'COMPRAS_CONFIG',

  // Configuración - Cashflow
  CASHFLOW_CONFIG: 'CASHFLOW_CONFIG',

  // Simulaciones de Cashflow
  CASHFLOW_SIMULACION_VER: 'CASHFLOW_SIMULACION_VER',
  CASHFLOW_SIMULACION_CREAR: 'CASHFLOW_SIMULACION_CREAR',
  CASHFLOW_SIMULACION_EDITAR: 'CASHFLOW_SIMULACION_EDITAR',
  CASHFLOW_SIMULACION_ELIMINAR: 'CASHFLOW_SIMULACION_ELIMINAR',
  RUTA_CASHFLOW_SIMULACIONES: 'RUTA_CASHFLOW_SIMULACIONES',

  // Rutas del menú - Config Compras
  RUTA_COMPRAS_CONFIG: 'RUTA_COMPRAS_CONFIG',

  // Rutas del menú - Config Cashflow
  RUTA_CASHFLOW_CONFIG: 'RUTA_CASHFLOW_CONFIG',

  // Rutas del menú - Reservas
  RUTA_RESERVAS: 'RUTA_RESERVAS',
  RUTA_RESERVAS_CREAR: 'RUTA_RESERVAS_CREAR',

  RUTA_INVENTARIO_EGRESO_MASIVO: 'RUTA_INVENTARIO_EGRESO_MASIVO',
  RUTA_INVENTARIO_INGRESO_MERCADERIA: 'RUTA_INVENTARIO_INGRESO_MERCADERIA',

  // Rutas del menú - Flota
  RUTA_FLOTA: 'RUTA_FLOTA',

  // Equipamiento
  EQUIPAMIENTO_VER: 'EQUIPAMIENTO_VER',
  EQUIPAMIENTO_CREAR: 'EQUIPAMIENTO_CREAR',
  EQUIPAMIENTO_EDITAR: 'EQUIPAMIENTO_EDITAR',
  EQUIPAMIENTO_ELIMINAR: 'EQUIPAMIENTO_ELIMINAR',

  // Rutas del menú - Equipamiento
  RUTA_EQUIPAMIENTO: 'RUTA_EQUIPAMIENTO',

  // Rutas del menú - Ubicaciones
  RUTA_UBICACIONES: 'RUTA_UBICACIONES',

  // Rutas del menú - Administración
  RUTA_ADMINISTRACION_FACTURACION: 'RUTA_ADMINISTRACION_FACTURACION',
  RUTA_NOTIFICACIONES_PLANTILLAS: 'RUTA_NOTIFICACIONES_PLANTILLAS',
  RUTA_ENVIOS_NOTIFICACION: 'RUTA_ENVIOS_NOTIFICACION',

  // Plantillas de notificación
  PLANTILLA_NOTIFICACION_VER: 'PLANTILLA_NOTIFICACION_VER',
  PLANTILLA_NOTIFICACION_CREAR: 'PLANTILLA_NOTIFICACION_CREAR',
  PLANTILLA_NOTIFICACION_EDITAR: 'PLANTILLA_NOTIFICACION_EDITAR',
  PLANTILLA_NOTIFICACION_ELIMINAR: 'PLANTILLA_NOTIFICACION_ELIMINAR',

  // Envíos de notificaciones
  ENVIO_NOTIFICACION_VER: 'ENVIO_NOTIFICACION_VER',
  ENVIO_NOTIFICACION_CREAR: 'ENVIO_NOTIFICACION_CREAR',
  ENVIO_NOTIFICACION_ELIMINAR: 'ENVIO_NOTIFICACION_ELIMINAR',

  // Configuración - Notificaciones
  NOTIFICACIONES_CONFIG: 'NOTIFICACIONES_CONFIG',

  // Rutas del menú - Config Notificaciones
  RUTA_NOTIFICACIONES_CONFIG: 'RUTA_NOTIFICACIONES_CONFIG',

  RUTA_PANEL_OPERARIO: 'RUTA_PANEL_OPERARIO',
  RUTA_ESTADISTICAS_PRODUCCION: 'RUTA_ESTADISTICAS_PRODUCCION',
  RUTA_ESTADO_PERSONAL: 'RUTA_ESTADO_PERSONAL',

  // Herramientas
  HERRAMIENTA_VER: 'HERRAMIENTA_VER',
  HERRAMIENTA_GESTIONAR: 'HERRAMIENTA_GESTIONAR',

  // Rutas del menú - Herramientas
  RUTA_HERRAMIENTAS: 'RUTA_HERRAMIENTAS',

} as const;

export type PermisosType = typeof PERMISOS[keyof typeof PERMISOS];
